modLoader="neoforge"
loaderVersion="[21.0.0,)"
license="MIT"

[[mods]]
modId="autosword"
version="${file.jarVersion}"
displayName="AutoSword"
description='''
A mod that automatically attacks with perfect sword timing, even when alt-tabbed or in menus.
'''
authors="AutoSwordDev"
credits=""
logoFile="logo.png"
url=""

[[dependencies.autosword]]
modId="neoforge"
mandatory=true
versionRange="[21.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.autosword]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="CLIENT"
